Updated user breakout diagrams
warthog-cpr/warthog-user-manual pull request #10
Opened 2017-10-20 20:39 UTC by majcote

- Updated system block diagram
- Updated user breakout

2017-10-20 20:57 UTC, tonybaltovski approved these changes

2017-10-23 20:41 UTC, tonybaltovski requested changes
In `User_Panel_Labeled.PNG` Serial is mislabelled as Ethernet.

2017-10-23 20:59 UTC, majcote commented
Fixed, please review

2017-10-23 21:00 UTC, tonybaltovski approved these changes

2017-10-23 21:00 UTC, merged

2017-10-23 21:01 UTC, tonybaltovski commented
Thanks @majcote